---
- name: Install apache
  apt: name=apache2 state=installed

- name: Set the base apache2.conf file
  template: src=apache2.conf.j2 dest=/etc/apache2/apache2.conf backup=yes
  notify: restart apache

- name: Enable some modules
  command: a2enmod {{ item }} creates=/etc/apache2/mods-enabled/{{ item }}.conf
  with_items:
    - proxy
    - proxy_balancer
    - proxy_ftp
    - php5
  notify: restart apache

- name: Enable some modules
  command: a2enmod {{ item }} creates=/etc/apache2/mods-enabled/{{ item }}.load
  with_items:
    - proxy_connect
    - proxy_ajp
    - proxy_http
    - proxy_scgi
    - rewrite
  notify: restart apache

- name: Disable the default site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache
